version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "node_modules:/app/node_modules"
    command: npm run dev -- -p 80

volumes:
  node_modules:
